name: ekko
description: A boilerplate for your project starts right.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  get: ^4.6.1
  get_storage: ^2.0.3
  logger: ^1.1.0
  equatable: ^2.0.3
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.4
  json_serializable: ^6.5.4
  faker: ^2.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true